GET http://localhost:8080/book?title=이해

###
#GET https://book-store.shop:8080/book?title=understand

POST http://localhost:8080/book
Content-Type: application/json

{
  "title": "제목",
  "publisher": "출판사",
  "author": "작가",
  "pubDate": "2024-06-20",
  "isbn": "isbn",
  "isbn13": "isbn13",
  "cover": "cover",
  "packable": true,
  "productDescription": "설명2",
  "productInventory": 1000,
  "productPriceStandard": 505000,
  "productPriceSales": 101000
}

###
POST localhost:8080/product/client/5/like
Cookie: JSESSIONID=75E29E91D2805BC070421DEA6FE8A48F; access=eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsInV1aWQiOiIwZTA1N2MwMy1mZTBlLTQxMjgtOWNjMi01MjFmZjc4M2E0ZTgiLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzE5NDQ5ODkxLCJleHAiOjE3MTk0NTcwOTF9.FRVyK9WW0PS899EeytZlGiSQEhhOne2LlhyGQr6sA7s; refresh=eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6InJlZnJlc2giLCJ1dWlkIjoiMGUwNTdjMDMtZmUwZS00MTI4LTljYzItNTIxZmY3ODNhNGU4Iiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTcxOTQ0OTg5MSwiZXhwIjoxNzIwNjU5NDkxfQ.uxdgooiBBVV4_FTyPEBk1YV80UfshLlET_dWFZR5STc;



###
POST localhost:8001/api/product/admin/tags/register
Content-Type: application/json

{
  "tagName" : "tagTag1"
}

###
POST localhost:8080/book
Content-Type: application/json

{
  "title": "제목",
  "publisher": "출판사",
  "author": "작가",
  "pubDate": "2024-06-20",
  "isbn": "isbn",
  "isbn13": "isbn13",
  "cover": "cover",
  "packable": false,
  "productDescription": "설명",
  "productInventory": 1012,
  "productPriceStandard": 5000012,
  "productPriceSales": 1000012,
  "categories": [
    "카테고리3", "카테고리5","카테고리6"
  ],
  "tags": [
    "tag1", "tag10"
  ]
}
